# Generated by Django 3.2.9 on 2021-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzdevumi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='lietotaji'),
        ),
        migrations.AlterField(
            model_name='user',
            name='epasts',
            field=models.EmailField(max_length=110),
        ),
        migrations.AlterField(
            model_name='user',
            name='lietotajs',
            field=models.CharField(max_length=100),
        ),
    ]
